"""Tool for confirming USDC payment for a discount code."""

from typing import Any, Optional, Type

from langchain_core.callbacks import CallbackManagerForToolRun
from langchain_core.tools import BaseTool
from pydantic import BaseModel, Field

from langchain_community.utilities.insumer import InsumerAPIWrapper


class InsumerConfirmPaymentSchema(BaseModel):
    """Input for InsumerConfirmPayment."""

    code: str = Field(
        description="Verification code from insumer_verify (e.g. INSR-A7K3M).",
    )
    tx_hash: str = Field(description="On-chain transaction hash or Solana signature.")
    chain_id: Any = Field(
        description=(
            "Chain where USDC was sent: 1 (Ethereum), 8453 (Base), "
            '137 (Polygon), 42161 (Arbitrum), 10 (Optimism), 56 (BNB), '
            '43114 (Avalanche), or "solana".'
        ),
    )
    amount: Any = Field(description="USDC amount sent.")


class InsumerConfirmPayment(BaseTool):
    """Confirm USDC payment for a discount code.

    After generating a code with ``insumer_verify``, confirm the customer's
    USDC payment. Server verifies the on-chain transaction receipt.
    """

    mode: str = "confirm_payment"
    name: str = "insumer_confirm_payment"
    description: str = (
        "Confirm USDC payment for a discount code generated by insumer_verify. "
        "Submit the verification code, USDC transaction hash, chain, and amount."
    )
    args_schema: Type[InsumerConfirmPaymentSchema] = InsumerConfirmPaymentSchema

    api_wrapper: InsumerAPIWrapper = Field(..., exclude=True)

    def __init__(self, api_wrapper: InsumerAPIWrapper) -> None:
        super().__init__(api_wrapper=api_wrapper)

    def _run(
        self,
        code: str,
        tx_hash: str,
        chain_id: Any,
        amount: Any,
        run_manager: Optional[CallbackManagerForToolRun] = None,
    ) -> str:
        """Confirm payment."""
        return self.api_wrapper.run(
            mode=self.mode,
            code=code,
            tx_hash=tx_hash,
            chain_id=chain_id,
            amount=amount,
        )
